name: CI Pipeline

on:
  pull_request:
    branches: [ main, master ]
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Check for package.json
      run: |
        if [ -f "package.json" ]; then
          echo "package.json found, installing dependencies..."
          npm install
          npm test || echo "No tests found"
        else
          echo "No package.json found, skipping Node.js steps."
        fi

    - name: Run basic checks
      run: |
        echo "✅ CI pipeline ran successfully!"
        echo "📄 Files in repo:"
        ls -la
